name: build

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      target:
        required: true
        type: string
      build-args:
        required: false
        type: string
      release-id:
        required: false
        type: string
      asset-prefix:
        required: false
        type: string
      asset-name-pattern:
        required: false
        type: string
      upload-artifacts:
        required: false
        type: boolean
      repository:
        required: false
        type: string
      ref:
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ inputs.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          filter: tree:0
          fetch-tags: true

      - name: Determine Version
        id: determine-version
        shell: bash
        run: |
          APP_VERSION=""
          REF="${{ inputs.ref }}"

          if [[ "$REF" == refs/tags/v* ]]; then
            APP_VERSION="${REF#refs/tags/v}"
            echo "Release version determined from tag: $APP_VERSION"
          else
            if [[ "${{ inputs.platform }}" == windows* ]]; then
              DESCRIBE="$(git describe --tags --always --abbrev=0)"
              APP_VERSION="${DESCRIBE#v}"
              echo "CI version determined from 'git describe': $APP_VERSION"
            else
              DESCRIBE="$(git describe --tags --always)"
              APP_VERSION="${DESCRIBE#v}"
              echo "CI version determined from 'git describe': $APP_VERSION"
            fi
          fi
          
          echo "version=${APP_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        if: startsWith(inputs.platform, 'macos')

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          key: ${{ inputs.platform }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install additional system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install frontend dependencies
        run: npm install

      - name: rustup install target
        if: ${{ inputs.target != '' }}
        run: rustup target add ${{ inputs.target }}

      - name: Set application version
        shell: bash
        run: |
          echo "Setting version to: ${{ steps.determine-version.outputs.version }}"
          npx tauri-version --no-git --no-lock "${{ steps.determine-version.outputs.version }}"

      - id: patch-release-name
        shell: bash
        if: ${{ inputs.release-id != '' }}
        run: |
          platform="${{ inputs.platform }}"
          replacement="$(echo ${platform} | sed -E 's/-latest//')"
          patched_platform=$(echo '${{ inputs.asset-name-pattern }}' | sed -E "s/\[platform\]/${replacement}/")
          if [[ -n "${{ inputs.asset-prefix }}" ]]; then
            patched_platform="${{ inputs.asset-prefix }}_${patched_platform}"
          fi
          echo "platform=${patched_platform}" >> $GITHUB_OUTPUT

      - id: tauri-build
        name: Build with tauri-action
        # FIXME set this back to a release major version, ex. v0 . This is a commit from the `dev` branch which includes PR
        # https://github.com/tauri-apps/tauri-action/pull/1099 , adding the assetNamePattern feature.
        uses: tauri-apps/tauri-action@cf3eb9b18add8548a40584695215c80ab7274f31
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NO_STRIP: ${{ startsWith(inputs.platform, 'ubuntu') }}
        with:
          args: ${{ inputs.build-args }} ${{ inputs.target != '' && '--target' || ''  }} ${{ inputs.target }}
          assetNamePattern: ${{ steps.patch-release-name.outputs.platform }}
          releaseId: ${{ inputs.release-id }}
          retryAttempts: 3

      - name: Setup gh actions artifact client
        if: ${{ inputs.release-id == '' }}
        uses: lhotari/gh-actions-artifact-client@v2

      - name: Upload binaries (Windows)
        shell: bash
        if: ${{ startsWith(inputs.platform, 'windows') && inputs.release-id == '' }}
        run: |
          find src-tauri/target/release/bundle -name "*.exe" | while read -r file; do
            name="${{ inputs.asset-prefix }}_${{ inputs.platform }}_$(basename "$file")"
            echo "Uploading $name, file: $file"
            # TODO zip the file before upload
            gh-actions-artifact-client.js upload "${name}" --retentionDays=7 < "$file"
          done

      - name: Upload binaries (Linux/macOS)
        if: ${{ !startsWith(inputs.platform, 'windows') && inputs.release-id == '' }}
        run: |
          find src-tauri/target/${{ inputs.target || 'release' }} -type f -name "*.rpm" -o -name "*.deb" -o -name "*.AppImage" -o -name "*.dmg" | while read -r file; do
            name="${{ inputs.asset-prefix }}_${{ inputs.platform }}_$(basename "$file")"
            echo "Uploading $name, file: $file"
            zip -j - "$file" | gh-actions-artifact-client.js upload "${name}" --retentionDays=7
          done
