name: CI Build

on:
  pull_request_target:

jobs:

  checkout-branch:
    runs-on: ubuntu-latest
    outputs:
      PR_head_ref: ${{ fromJSON(steps.comment-branch.outputs.result).ref }}
      PR_head_sha: ${{ fromJSON(steps.comment-branch.outputs.result).sha }}
      PR_num: ${{ fromJSON(steps.comment-branch.outputs.result).num }}
      PR_repo: ${{ fromJSON(steps.comment-branch.outputs.result).repo }}
    permissions:
      pull-requests: read
    steps:
    - uses: actions/github-script@v7
      id: comment-branch
      with:
        script: |
          const result = await github.rest.pulls.get ({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          })
          return { repo: result.data.head.repo.full_name, num: result.data.number, sha: result.data.head.sha, ref: result.data.head.ref }

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            builds-args: '--bundles nsis'
            target: ''
            asset-prefix: '01'
          - platform: 'macos-13'
            target: aarch64-apple-darwin
            asset-prefix: '02'
          - platform: 'macos-13'
            target: x86_64-apple-darwin
            asset-prefix: '02'
          - platform: 'ubuntu-22.04'
            target: ''
            asset-prefix: '03'
          - platform: 'ubuntu-22.04-arm'
            target: ''
            asset-prefix: '03'
          - platform: 'ubuntu-24.04'
            target: ''
            asset-prefix: '03'
          - platform: 'ubuntu-24.04-arm'
            target: ''
            asset-prefix: '03'
    uses: ./.github/workflows/build.yml
    needs: [checkout-branch]
    with:
      repository: ${{ needs.checkout-branch.outputs.PR_repo }}
      ref: ${{ needs.checkout-branch.outputs.PR_head_ref }}
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      asset-prefix: ${{ matrix.asset-prefix }}
    secrets: inherit
    permissions:
      contents: write
